conf: set higher layer priority than meta-ivi
Since both layers are patching same recipe,
it's safer to force the patch series order
than just relying on order of layers' listed in bblayers.conf

Now meta-genivi-demo priority is set from 7 to 8
while meta-ivi still remains 7.

Without this change, user can face a build error in this form :

  ERROR: Command Error: exit status: 1  Output:
  Applying patch browser_poc_hack.patch
  can't find file to patch at input line 4
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -rupN weston-1.5.0.orig/ivi-shell/hmi-controller.c weston-1.5.0/ivi-shell/hmi-controller.c
  |--- weston-1.5.0.orig/ivi-shell/hmi-controller.c       2014-10-17 15:58:46.327999060 +0200
  |+++ weston-1.5.0/ivi-shell/hmi-controller.c    2014-10-17 16:01:56.515996303 +0200
  --------------------------
  No file to patch.  Skipping patch.
  1 out of 1 hunk ignored
  Patch browser_poc_hack.patch does not apply (enforce with -f)
  ERROR: Function failed: patch_do_patch

Bug: https://at.projects.genivi.org/jira/browse/GDP-17#related
Origin: https://github.com/TizenTeam/meta-genivi-demo/tree/sandbox/pcoval/for/upstream/master
Cc: genivi-projects@lists.genivi.org
Change-Id: Ic02973ea97d97d87ab64f012e6e87882d9491258
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>